/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Medicine {
  'id' : bigint,
  'dosage' : string,
  'expiryDate' : string,
  'name' : string,
  'quantity' : bigint,
  'category' : string,
  'unitPrice' : number,
  'isNearExpiry' : boolean,
  'supplierId' : bigint,
}
export interface Sale {
  'id' : bigint,
  'patientName' : string,
  'quantity' : bigint,
  'category' : string,
  'unitPrice' : number,
  'totalPrice' : number,
  'medicineId' : bigint,
  'saleDate' : string,
  'medicineName' : string,
}
export interface Supplier { 'id' : bigint, 'contact' : string, 'name' : string }
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMedicine' : ActorMethod<
    [string, string, string, bigint, bigint, number, string, boolean],
    Medicine
  >,
  'addSupplier' : ActorMethod<[string, string], Supplier>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMedicine' : ActorMethod<[bigint], boolean>,
  'deleteSupplier' : ActorMethod<[bigint], boolean>,
  'getAnalyticsSummary' : ActorMethod<
    [],
    {
      'totalSales' : bigint,
      'totalMedicines' : bigint,
      'totalRevenue' : number,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryDemand' : ActorMethod<
    [],
    Array<
      { 'feb' : bigint, 'jan' : bigint, 'mar' : bigint, 'category' : string }
    >
  >,
  'getMedicines' : ActorMethod<[], Array<Medicine>>,
  'getMonthlySalesTrend' : ActorMethod<
    [],
    Array<{ 'month' : string, 'totalSales' : bigint, 'totalRevenue' : number }>
  >,
  'getNearExpiryAlerts' : ActorMethod<[], Array<Medicine>>,
  'getSales' : ActorMethod<[], Array<Sale>>,
  'getSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordSale' : ActorMethod<[bigint, bigint, string, string], [] | [Sale]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMedicine' : ActorMethod<
    [bigint, string, string, string, bigint, bigint, number, string, boolean],
    [] | [Medicine]
  >,
  'updateSupplier' : ActorMethod<[bigint, string, string], [] | [Supplier]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];