/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Medicine = IDL.Record({
  'id' : IDL.Nat,
  'dosage' : IDL.Text,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'isNearExpiry' : IDL.Bool,
  'supplierId' : IDL.Nat,
});
export const Supplier = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'name' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'patientName' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
  'medicineId' : IDL.Nat,
  'saleDate' : IDL.Text,
  'medicineName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMedicine' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
        IDL.Bool,
      ],
      [Medicine],
      [],
    ),
  'addSupplier' : IDL.Func([IDL.Text, IDL.Text], [Supplier], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMedicine' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSupplier' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAnalyticsSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalSales' : IDL.Nat,
          'totalMedicines' : IDL.Nat,
          'totalRevenue' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryDemand' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'feb' : IDL.Nat,
            'jan' : IDL.Nat,
            'mar' : IDL.Nat,
            'category' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getMonthlySalesTrend' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'month' : IDL.Text,
            'totalSales' : IDL.Nat,
            'totalRevenue' : IDL.Float64,
          })
        ),
      ],
      ['query'],
    ),
  'getNearExpiryAlerts' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordSale' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Opt(Sale)],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMedicine' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Opt(Medicine)],
      [],
    ),
  'updateSupplier' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Opt(Supplier)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Medicine = IDL.Record({
    'id' : IDL.Nat,
    'dosage' : IDL.Text,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'isNearExpiry' : IDL.Bool,
    'supplierId' : IDL.Nat,
  });
  const Supplier = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'name' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'patientName' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
    'medicineId' : IDL.Nat,
    'saleDate' : IDL.Text,
    'medicineName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMedicine' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
        ],
        [Medicine],
        [],
      ),
    'addSupplier' : IDL.Func([IDL.Text, IDL.Text], [Supplier], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMedicine' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSupplier' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAnalyticsSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalSales' : IDL.Nat,
            'totalMedicines' : IDL.Nat,
            'totalRevenue' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryDemand' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'feb' : IDL.Nat,
              'jan' : IDL.Nat,
              'mar' : IDL.Nat,
              'category' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getMonthlySalesTrend' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'month' : IDL.Text,
              'totalSales' : IDL.Nat,
              'totalRevenue' : IDL.Float64,
            })
          ),
        ],
        ['query'],
      ),
    'getNearExpiryAlerts' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordSale' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Opt(Sale)],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMedicine' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Opt(Medicine)],
        [],
      ),
    'updateSupplier' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Opt(Supplier)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };